(function(){
function money(n){try{return new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD'}).format(+n||0)}catch(e){return '$'+(+n||0).toFixed(2)}}
function monthPunches(){if(typeof USER==='undefined'||!USER||typeof DB==='undefined')return[];var now=new Date();return (DB.punches||[]).filter(function(p){if(p.qui!==USER.name)return false;var d=new Date(p.in);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});}
function statsMois(){var mine=monthPunches();return {n:mine.length,h:mine.reduce(function(s,p){return s+(p.heures||0)},0),$:mine.reduce(function(s,p){return s+(p.gain!=null?p.gain:(p.heures||0)*((USER&&USER.taux)||0))},0),pose:mine.reduce(function(s,p){return s+(p.poseQty||0)},0)};}
function prix(){if(typeof DB==='undefined'||!DB.produits)return '';return DB.produits.map(function(p){return p.sku+' '+p.nom+' — fourn. '+money(p.four)+' · ST '+money(p.sous)+' · client '+money(p.client)+' / '+(p.unite||'');}).join('\n');}
function answer(raw){var q=(raw||'').toLowerCase();if(!q.trim())return 'Paie, stats du mois, ou un problème de chantier.';
if(/paye|paie|salaire|taux|piastre|combien/.test(q)){if(!USER)return 'Connecte-toi.';var st=statsMois();return USER.name+' · mode '+(USER.payMode||'heure')+' · '+money(USER.taux||0)+'/h.\nMois : '+st.h.toFixed(1)+' h, '+money(st.$);}
if(/stat|mois|heure|punch/.test(q)){var s=statsMois();return 'Mois : '+s.n+' punchs, '+s.h.toFixed(1)+' h, '+money(s.$)+(s.pose?', posé '+s.pose:'');
}
if(/prix|catalogue|home depot|vinyle|fascia|soffit|mat[eé]riau/.test(q))return 'Catalogue :\n'+prix()+'\nCalgary : Home Depot, RONA, Gentek/Kaycan/Mitten.';
if(/vinyle|siding|bardage/.test(q))return 'Vinyle D4 : starter en bas, joints décalés 24 po, clous au centre du slot, jeu 1/4 po au froid Calgary. Matos : J-channel, coins, clous galva, housewrap.\n'+prix();
if(/soffit|fascia/.test(q))return 'Soffit venté, fascia droit, vis galva. Remplacer le bois pourri avant de recouvrir.';
if(/gr[eê]le|hail/.test(q))return 'Photos avant/après + pi²/mur. Remplacer si fissure, pas seulement bosse.';
if(/[eé]chafaud|[eé]chelle/.test(q))return 'Niveau, semelles, garde-corps 3 m, hold si vent.';
return 'Ingénieur siding / soffit / grêle / hiver AB. Demande aussi « mon taux » ou « stats mois ».';}
function ensure(){if(typeof USER==='undefined'||!USER||USER.portal!=='staff'){var o=document.getElementById('gm-ai');if(o)o.remove();return;}if(document.getElementById('gm-ai'))return;var w=document.createElement('div');w.id='gm-ai';w.innerHTML='<button class="gm-ai-fab" id="gm-ai-fab">IA</button><div class="gm-ai-panel" id="gm-ai-panel" hidden><header>IA chantier + paie</header><div class="gm-ai-log" id="gm-ai-log"><p class="muted">Paie, stats, ou un problème de pose.</p></div><div class="gm-ai-row"><input id="gm-ai-q" placeholder="Ex. joints vinyle / mon taux"><button class="btn sm" id="gm-ai-go">OK</button></div></div>';document.body.appendChild(w);document.getElementById('gm-ai-fab').onclick=function(){var p=document.getElementById('gm-ai-panel');p.hidden=!p.hidden};function send(){var inp=document.getElementById('gm-ai-q'),log=document.getElementById('gm-ai-log'),q=inp.value;if(!q.trim())return;log.innerHTML+='<p><b>Toi</b> '+q.replace(/</g,'')+'</p><p><b>IA</b> '+answer(q).replace(/\n/g,'<br>')+'</p>';inp.value='';log.scrollTop=log.scrollHeight;}document.getElementById('gm-ai-go').onclick=send;document.getElementById('gm-ai-q').addEventListener('keydown',function(e){if(e.key==='Enter')send();});}
var css=document.createElement('style');css.textContent='#gm-ai{position:fixed;right:16px;bottom:16px;z-index:40}.gm-ai-fab{width:56px;height:56px;border-radius:50%;background:linear-gradient(180deg,#efc56a,#c9963a);color:#1a1206;font-weight:800;border:0}.gm-ai-panel{position:absolute;right:0;bottom:68px;width:min(340px,calc(100vw - 24px));background:#161920;border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px}.gm-ai-log{max-height:240px;overflow:auto;font-size:13px}.gm-ai-row{display:flex;gap:6px;margin-top:8px}.gm-ai-row input{flex:1}';document.head.appendChild(css);setInterval(ensure,800);})();
